# Generated by Django 2.0.7 on 2019-07-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20190714_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('B', 'Books'), ('El', 'Electronics'), ('St', 'Stationary'), ('Fa', 'Fashion'), ('Sp', 'Sports'), ('Ot', 'Others')], default='', max_length=50),
        ),
    ]
