# Generated by Django 2.1.7 on 2019-07-17 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='document',
            new_name='image',
        ),
    ]
