# Generated by Django 2.1.7 on 2019-07-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20190721_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('books', 'BOOKS'), ('electronics', 'ELECTRONICS'), ('fashion', 'FASHION'), ('stationary', 'STATIONARY'), ('others', 'OTHERS')], default='', max_length=12),
        ),
    ]
